version: '3.9'
services:
  app:
    build: .
    container_name: app
    image: app
    environment:
      PG_URL: 'postgres://user:pass@postgres:5432/postgres'
    ports:
      - 8080:8080
    depends_on:
      - postgres         


  postgres:
    container_name: postgresGo
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=go-db
    ports:
      - 5432:5432
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgres
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  pg-data: